// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLsentiment
{
    public partial class MLRecommendation
    {
        /// <summary>
        /// model input class for MLRecommendation.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"CustomerID")]
            public float CustomerID { get; set; }

            [ColumnName(@"DestinationID")]
            public float DestinationID { get; set; }

            [ColumnName(@"RoundedValue")]
            public float RoundedValue { get; set; }

            [ColumnName(@"key")]
            public float Key { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLRecommendation.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"CustomerID")]
            public uint CustomerID { get; set; }

            [ColumnName(@"DestinationID")]
            public uint DestinationID { get; set; }

            [ColumnName(@"RoundedValue")]
            public float RoundedValue { get; set; }

            [ColumnName(@"key")]
            public float Key { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = @"D:\CuoiKy\CuoiKy\MLsentiment\MLRecommendation.zip";

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
